### ISSUE TITLE
[BUG] send_notification not sending a notification on gnome 40.2.0

### ISSUE THREAD

**Issue by kpcyrd** [gtk-rs/gtk3-rs#611] opened 2021-07-13 21:01 UTC
**Bug description**

I'm trying to send a notification with [`send_notification`](https://docs.rs/gtk/0.14.0/gtk/struct.Application.html#method.send_notification). The click registers since `clicked` is printed, but no notification shows up.

```rust
use gtk::gio::Notification;
use gtk::glib;
use gtk::prelude::*;

fn build_ui(application: &gtk::Application) {
    let window = gtk::ApplicationWindow::new(application);

    window.set_title("First GTK+ Program");
    window.set_border_width(10);
    window.set_position(gtk::WindowPosition::Center);
    window.set_default_size(350, 70);

    let button = gtk::Button::with_label("Click me!");
    button.connect_clicked(glib::clone!(@weak application => move |_| {
        let app = &application;
        println!("clicked");
        let notification = Notification::new("foo");
        app.send_notification(None, &notification);
    }));

    window.add(&button);

    window.show_all();
}

fn main() {
    let application =
        gtk::Application::new(Some("com.github.gtk-rs.examples.basic"), Default::default());

    application.connect_activate(build_ui);

    application.run();
}
```

**Comment by bilelmoussaoui** [comment] 2021-07-13 21:10
Duplicate of #522

**Closed** 2021-07-13 21:11 UTC
Labels: bug, duplicate
