### ISSUE TITLE
Implement `ToValue` for `Value` again

### ISSUE THREAD

**Issue by piegamesde** [gtk-rs/gtk3-rs#605] opened 2021-06-29 20:53 UTC
Please revert https://github.com/gtk-rs/glib/commit/390ca3a2. Conversion traits in Rust are usually expected to be reflexive. Things can get weird if you don't: For example, the [`GtkListStoreExtManual::set`](https://gtk-rs.org/gtk3-rs/stable/latest/docs/gtk/prelude/trait.GtkListStoreExtManual.html#tymethod.set) method accepts a `&dyn ToValue`. This makes sense because it allows the user to provide multiple values of different types in an array without requiring conversion, which is convenient.

But if I have some `Value`s that I got from somewhere and `ToValue` is not reflexive, then I suddenly cannot use that method anymore. As a workaround there is `set_value`, but it can only deal with one column at a time.

CC @sophie-h

**Comment by piegamesde** [comment] 2021-06-29 22:31
I don't think this would be a good solution. Imagine having a function:

```rust
pub fn read<P: AsRef<Path>>(path: P) -> Result<Vec<u8>>
```

except that I can't call it with a `&Path`, because `&Path` does not implement `AsRef<Path>`. And now imagine the obvious solution being to have a second method (name subject to bikeshedding):

```rust
pub fn read2(path: &Path) -> Result<Vec<u8>>
```

------

I'd say making `set` accept only a `&Value` would be a fine alternative solution. Then, it'd be up to the user to call `to_value()`. But I suggest going in the other direction and let every function that currently wants a `&Value` accept a `&impl ToValue` (though this is not the subject of this issue).

**Comment by sdroege** [comment] 2021-06-30 05:54
The problem here is that `ToValue` is wrapping a value of some type into a `Value`. If you implement it also on `Value` itself then you would expect it to create a `Value` that contains a `Value` (which it previously did, but that got its own wrapper type now because it's very rarely needed and caused confusion), not that it wouldn't do anything at all.

This is different from `AsRef<Path>` in the sense that that always gives you a reference to a `Path`.

OTOH the `impl<T> From<T> for T` and as a result `impl<T> Into<T> for T` is a no-op so maybe what you suggest actually makes sense. The question then is if that would be more or less confusing than a separate function (and a problem with that is that it would need a lot of separate functions).

**Comment by sdroege** [comment] 2021-06-30 10:51
Duplicate of https://github.com/gtk-rs/gtk-rs-core/issues/4 btw

**Closed by sdroege** 2021-06-30 10:51 UTC
Labels: good first issue, gtk
